
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATE = 29;
  public static final int LONG = 14;
  public static final int NATURAL = 16;
  public static final int ELSE = 33;
  public static final int DOTCOMMA = 15;
  public static final int PLUS = 22;
  public static final int INT = 11;
  public static final int WHILE = 34;
  public static final int PRIVATE = 6;
  public static final int IF = 32;
  public static final int ID = 3;
  public static final int PUBLIC = 7;
  public static final int PROGRAM = 2;
  public static final int STATIC = 9;
  public static final int GREAT = 27;
  public static final int COMMA = 10;
  public static final int FLOAT = 12;
  public static final int PROTECTED = 8;
  public static final int EOF = 0;
  public static final int MAIN = 19;
  public static final int DIV = 24;
  public static final int MINUS = 25;
  public static final int error = 1;
  public static final int EQ = 30;
  public static final int ASSIGN = 18;
  public static final int SOBRACKET = 20;
  public static final int SCBRACKET = 21;
  public static final int LESSE = 28;
  public static final int REAL = 17;
  public static final int NEQ = 31;
  public static final int MUL = 23;
  public static final int LOBRACKET = 4;
  public static final int LESS = 26;
  public static final int LCBRACKET = 5;
  public static final int DOUBLE = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "ID",
  "LOBRACKET",
  "LCBRACKET",
  "PRIVATE",
  "PUBLIC",
  "PROTECTED",
  "STATIC",
  "COMMA",
  "INT",
  "FLOAT",
  "DOUBLE",
  "LONG",
  "DOTCOMMA",
  "NATURAL",
  "REAL",
  "ASSIGN",
  "MAIN",
  "SOBRACKET",
  "SCBRACKET",
  "PLUS",
  "MUL",
  "DIV",
  "MINUS",
  "LESS",
  "GREAT",
  "LESSE",
  "GREATE",
  "EQ",
  "NEQ",
  "IF",
  "ELSE",
  "WHILE"
  };

}

